/** Rich demo content used to seed the SQLite database */

export type SeedEvent = {
  id: string;
  title: string;
  dateLabel: string;
  summary: string;
  badge?: string;
  location?: string;
  status: 'upcoming' | 'past';
  recurring?: boolean;
  details?: string[];
  scheduleKind?: string;
  hub?: 'youth' | 'sisters' | 'seniors' | null;
  startsAt?: string;
  endsAt?: string;
  sortOrder?: number;
};

export type SeedProgram = {
  id: string;
  category: 'education' | 'community' | 'service';
  title: string;
  summary: string;
  schedule?: string;
  tags?: string[];
  hub?: 'youth' | 'sisters' | 'seniors' | null;
  sortOrder?: number;
};

export const seedEventsExtra: SeedEvent[] = [
  // ── Youth ──────────────────────────────────────────────
  {
    id: 'youth-friday',
    title: 'Friday Youth Programme',
    dateLabel: 'Every Friday after Isha',
    summary:
      'Small talk with refreshments, followed by basketball — a weekly night for youth to connect after Isha.',
    badge: 'Youth',
    location: 'Masjid Darus Salaam',
    status: 'upcoming',
    recurring: true,
    hub: 'youth',
    details: ['Starts after Isha', 'Short talk with refreshments', 'Basketball afterward'],
  },
  {
    id: 'brothers-basketball',
    title: 'Brothers Basketball Programme',
    dateLabel: 'Every Saturday · Zuhr iqamah to +3 hours',
    summary:
      'Ages 16–25 · 8 weeks · Seerah talks · 5v5 full-court with scoreboard. No late entries — gym closes 30 min after Zuhr iqamah.',
    badge: 'Youth',
    location: 'IST Gym',
    status: 'upcoming',
    recurring: true,
    scheduleKind: 'zuhr-window',
    hub: 'youth',
    details: [
      'Ages 16–25',
      '8-week programme',
      'Seerah of the Prophet ﷺ',
      '5v5 full-court games',
      'Gym closes 30 min after Zuhr iqamah',
    ],
  },
  {
    id: 'youth-quran-circle',
    title: 'Youth Quran Circle',
    dateLabel: 'Sundays · 11:00 AM – 12:30 PM',
    summary: 'Peer-led tilawah and tafsir discussion for brothers ages 13–25 in a welcoming circle.',
    badge: 'Youth',
    location: 'Classroom B',
    status: 'upcoming',
    recurring: true,
    hub: 'youth',
    details: ['Ages 13–25', 'Bring your mushaf', 'Light snacks provided'],
  },
  {
    id: 'youth-leadership',
    title: 'Youth Leadership Workshop',
    dateLabel: 'Saturday, August 16 · 2:00–5:00 PM',
    summary: 'Hands-on workshop on khidmah, public speaking, and organising community programmes.',
    badge: 'Youth',
    location: 'Main hall',
    status: 'upcoming',
    hub: 'youth',
    startsAt: '2026-08-16T14:00:00-04:00',
    endsAt: '2026-08-16T17:00:00-04:00',
    details: ['Open to ages 15–25', 'Registration preferred', 'Certificates on completion'],
  },
  {
    id: 'youth-camp-past',
    title: 'Summer Youth Day Camp',
    dateLabel: 'July 10–12, 2026',
    summary: 'Three-day day camp with sports, crafts, and Islamic workshops for ages 10–16.',
    badge: 'Youth',
    location: 'IST Campus',
    status: 'past',
    hub: 'youth',
    startsAt: '2026-07-10T09:00:00-04:00',
    endsAt: '2026-07-12T16:00:00-04:00',
  },

  // ── Sisters ────────────────────────────────────────────
  {
    id: 'sisters-volleyball',
    title: 'Sisters Drop-in Volleyball',
    dateLabel: 'Wednesday, August 12 · 8:00–10:00 PM',
    summary: 'Sisters-only drop-in volleyball. Come play and connect.',
    badge: 'Sisters',
    location: 'IST Gym',
    status: 'upcoming',
    hub: 'sisters',
    startsAt: '2026-08-12T20:00:00-04:00',
    endsAt: '2026-08-12T22:00:00-04:00',
    details: ['Sisters only', 'Drop-in', '8:00 PM – 10:00 PM'],
  },
  {
    id: 'sisters-self-care',
    title: 'Sisters Self-Care Evening',
    dateLabel: 'Saturday, August 30 · 6:00–8:30 PM',
    summary: 'An evening of mindfulness, dua, and wellness tips for sisters — light refreshments included.',
    badge: 'Sisters',
    location: 'Sisters wing',
    status: 'upcoming',
    hub: 'sisters',
    startsAt: '2026-08-30T18:00:00-04:00',
    endsAt: '2026-08-30T20:30:00-04:00',
  },
  {
    id: 'sisters-halaqa',
    title: "Sisters' Weekly Halaqa",
    dateLabel: 'Thursdays after Maghrib',
    summary: 'Tafsir and seerah circle for sisters with childcare available on request.',
    badge: 'Sisters',
    location: 'Sisters wing',
    status: 'upcoming',
    recurring: true,
    hub: 'sisters',
    details: ['After Maghrib', 'Childcare on request', 'Open to all sisters'],
  },
  {
    id: 'sisters-fitness',
    title: 'Sisters Fitness & Wellness',
    dateLabel: 'Mondays · 7:30–8:30 PM',
    summary: 'Low-impact fitness class in a sisters-only space focused on strength and wellness.',
    badge: 'Sisters',
    location: 'IST Gym',
    status: 'upcoming',
    recurring: true,
    hub: 'sisters',
    details: ['Sisters only', 'Bring a mat', 'Beginner friendly'],
  },
  {
    id: 'sisters-book-club',
    title: 'Sisters Book Club',
    dateLabel: 'First Sunday each month · 3:00 PM',
    summary: 'Monthly discussion of classical and contemporary Islamic literature for sisters.',
    badge: 'Sisters',
    location: 'Library room',
    status: 'upcoming',
    recurring: true,
    hub: 'sisters',
  },
  {
    id: 'sisters-iftar-past',
    title: 'Sisters Community Iftar',
    dateLabel: 'March 15, 2026',
    summary: 'Ramadan iftar and short reminder organised by the Sisters’ Hub.',
    badge: 'Sisters',
    location: 'Main hall',
    status: 'past',
    hub: 'sisters',
    endsAt: '2026-03-15T21:00:00-04:00',
  },

  // ── Seniors ────────────────────────────────────────────
  {
    id: 'seniors-tea',
    title: 'Seniors Tea & Companionship',
    dateLabel: 'Tuesdays · 11:00 AM – 1:00 PM',
    summary: 'Weekly tea, Quran listening, and social time for elders of our community.',
    badge: 'Seniors',
    location: 'Community lounge',
    status: 'upcoming',
    recurring: true,
    hub: 'seniors',
    details: ['Light refreshments', 'Family members welcome to drop off', 'Urdu & English'],
  },
  {
    id: 'seniors-health',
    title: 'Seniors Health Talk',
    dateLabel: 'Saturday, August 9 · 11:00 AM',
    summary: 'Guest talk on heart health and mobility with Q&A, organised with local clinicians.',
    badge: 'Seniors',
    location: 'Classroom A',
    status: 'upcoming',
    hub: 'seniors',
    startsAt: '2026-08-09T11:00:00-04:00',
    endsAt: '2026-08-09T12:30:00-04:00',
  },
  {
    id: 'seniors-quran',
    title: 'Seniors Quran Listening Circle',
    dateLabel: 'Fridays after Jummah',
    summary: 'Calm tilawah listening and short reminders tailored for our elders.',
    badge: 'Seniors',
    location: 'Prayer hall side room',
    status: 'upcoming',
    recurring: true,
    hub: 'seniors',
  },
  {
    id: 'seniors-outing-past',
    title: 'Seniors Garden Outing',
    dateLabel: 'June 21, 2026',
    summary: 'Day outing to a local garden with packed lunch and companionship volunteers.',
    badge: 'Seniors',
    location: 'Off-site',
    status: 'past',
    hub: 'seniors',
    endsAt: '2026-06-21T16:00:00-04:00',
  },

  // ── General / sports / community ───────────────────────
  {
    id: 'jummah',
    title: 'Friday Jummah Prayer',
    dateLabel: 'Every Friday',
    summary:
      'Join the congregation for khutbah and Jummah prayer. Multiple congregations each week — check the prayer board for times.',
    badge: 'Weekly',
    location: '20 Overlea Blvd',
    status: 'upcoming',
    recurring: true,
  },
  {
    id: 'badminton-dropin',
    title: 'Badminton Registered Drop-in',
    dateLabel: 'Tuesday, July 28 · 8:00–10:00 PM',
    summary: 'Registered drop-in badminton for ages 16+.',
    badge: 'Sports',
    location: 'IST Gym',
    status: 'past',
    startsAt: '2026-07-28T20:00:00-04:00',
    endsAt: '2026-07-28T22:00:00-04:00',
    details: ['Ages 16+', 'Registered drop-in'],
  },
  {
    id: 'family-picnic',
    title: 'Community Family Picnic',
    dateLabel: 'Sunday, August 24 · 12:00–4:00 PM',
    summary: 'Open picnic for IST families with games, food stalls, and a short programme for kids.',
    badge: 'Community',
    location: 'Flemingdon Park (details TBA)',
    status: 'upcoming',
    startsAt: '2026-08-24T12:00:00-04:00',
    endsAt: '2026-08-24T16:00:00-04:00',
  },
  {
    id: 'new-muslim-circle',
    title: 'New Muslim Circle',
    dateLabel: 'Saturdays · 4:00–5:30 PM',
    summary: 'Supportive circle for new Muslims covering essentials of salah, aqidah, and community life.',
    badge: 'Community',
    location: 'Classroom C',
    status: 'upcoming',
    recurring: true,
  },
  {
    id: 'open-house',
    title: 'Masjid Open House',
    dateLabel: 'Saturday, September 6 · 10:00 AM – 2:00 PM',
    summary: 'Tour the facility, meet Imams and teachers, and learn about programmes for every age.',
    badge: 'Featured',
    location: '20 Overlea Blvd',
    status: 'upcoming',
    startsAt: '2026-09-06T10:00:00-04:00',
    endsAt: '2026-09-06T14:00:00-04:00',
  },
  {
    id: 'fundraiser-dinner',
    title: 'Annual Fundraising Dinner',
    dateLabel: 'Saturday, October 18 · 6:00 PM',
    summary: 'An evening of dinner, reminders, and support for education and facilities at Masjid Darus Salaam.',
    badge: 'Featured',
    location: 'Main hall',
    status: 'upcoming',
    startsAt: '2026-10-18T18:00:00-04:00',
    endsAt: '2026-10-18T22:00:00-04:00',
  },
  {
    id: 'eid-ul-fitr-past',
    title: 'Eid ul-Fitr Prayer',
    dateLabel: 'March 31, 2026',
    summary: 'Congregational Eid prayer and community greeting in the main hall and overflow spaces.',
    badge: 'Eid',
    location: '20 Overlea Blvd',
    status: 'past',
    endsAt: '2026-03-31T10:00:00-04:00',
  },
  {
    id: 'youth-qiyam-past',
    title: 'Youth Qiyam Night',
    dateLabel: 'May 17, 2026',
    summary: 'Overnight qiyam with talks, Quran, and suhoor for brothers ages 14–25.',
    badge: 'Youth',
    location: 'IST Campus',
    status: 'past',
    hub: 'youth',
    endsAt: '2026-05-17T05:00:00-04:00',
  },
  {
    id: 'sisters-retreat-past',
    title: 'Sisters Half-Day Retreat',
    dateLabel: 'April 26, 2026',
    summary: 'Half-day retreat with workshops on iman, sisterhood, and practical deen for daily life.',
    badge: 'Sisters',
    location: 'Main hall',
    status: 'past',
    hub: 'sisters',
    endsAt: '2026-04-26T15:00:00-04:00',
  },
  {
    id: 'tarawih-info-past',
    title: 'Taraweeh Orientation Night',
    dateLabel: 'February 28, 2026',
    summary: 'Pre-Ramadan orientation covering taraweeh schedule, volunteer roles, and iftar logistics.',
    badge: 'Community',
    location: 'Main hall',
    status: 'past',
    endsAt: '2026-02-28T21:00:00-04:00',
  },
];

export const seedProgramsExtra: SeedProgram[] = [
  // Education (core + extras)
  {
    id: 'madressa',
    category: 'education',
    title: 'Evening Quran & Madressa',
    summary: 'Weekday evening classes for children ages 6–16 covering Quran, Islamic studies, and adab.',
    schedule: 'Monday – Friday: 5:15 – 7:15 PM',
    tags: ['Ages 6–16', 'Children'],
  },
  {
    id: 'sunday',
    category: 'education',
    title: 'Sunday Madrasah',
    summary: 'Weekend Quran and Islamic teachings for ages 6–16 in a welcoming classroom setting.',
    schedule: 'Sunday: 10:30 AM – 2:00 PM',
    tags: ['Weekend', 'Children'],
  },
  {
    id: 'hifz',
    category: 'education',
    title: 'Hifz Program',
    summary: 'Memorise the Quran with Tajweed — full-time day track or part-time evening schedule.',
    schedule: 'Full-Time Mon–Fri 8:15 AM – 3:00 PM · Part-Time 4:40 – 7:30 PM',
    tags: ['Full-time', 'Part-time'],
  },
  {
    id: 'alim',
    category: 'education',
    title: 'Alim Program',
    summary: 'Multi-year intensive covering Arabic, Fiqh, Hadith, Quran, and Islamic sciences.',
    schedule: 'Full-Time Mon–Fri 8:00 AM – 3:00 PM · Part-Time 4:40 – 7:30 PM',
    tags: ['6-year track'],
  },
  {
    id: 'essentials',
    category: 'education',
    title: 'Islamic Essentials — Advanced Maktab',
    summary: 'Two-year course for high school students on creed, jurisprudence, and ethics.',
    tags: ['High school', 'Youth'],
    hub: 'youth',
  },
  {
    id: 'adults',
    category: 'education',
    title: 'Adult Tajweed & Arabic',
    summary: 'Quran recitation and Arabic fundamentals paced for busy adults.',
    tags: ['Adults'],
  },
  {
    id: 'kids-story',
    category: 'education',
    title: 'Kids Seerah Story Hour',
    summary: 'Interactive seerah stories and crafts for younger children after Sunday Madrasah.',
    schedule: 'Sundays 2:15 – 3:00 PM',
    tags: ['Children', 'Ages 5–10'],
  },
  {
    id: 'youth-mentorship',
    category: 'education',
    title: 'Youth Mentorship Track',
    summary: 'Monthly mentoring circles pairing youth with older brothers for deen and life guidance.',
    schedule: 'First Friday each month',
    tags: ['Youth', 'Mentorship'],
    hub: 'youth',
  },

  // Sisters programmes (id matches /community/sisters)
  {
    id: 'sisters',
    category: 'community',
    title: "Sisters' Hub",
    summary: 'Dedicated programmes, classes, and gatherings for women at IST.',
    tags: ['Sisters'],
    hub: 'sisters',
  },
  {
    id: 'sisters-tajweed',
    category: 'education',
    title: 'Sisters Tajweed Class',
    summary: 'Beginner-to-intermediate tajweed for sisters with experienced female instructors.',
    schedule: 'Tuesdays & Thursdays · 10:00 – 11:30 AM',
    tags: ['Sisters', 'Tajweed'],
    hub: 'sisters',
  },
  {
    id: 'sisters-parenting',
    category: 'community',
    title: 'Sisters Parenting Circle',
    summary: 'Monthly discussions on raising children with iman, adab, and practical parenting tools.',
    schedule: 'Second Saturday · 11:00 AM',
    tags: ['Sisters', 'Family'],
    hub: 'sisters',
  },
  {
    id: 'sisters-arabic',
    category: 'education',
    title: 'Sisters Arabic Foundations',
    summary: 'Introductory Arabic reading and vocabulary for sisters, paced for beginners.',
    schedule: 'Wednesdays · 11:00 AM – 12:30 PM',
    tags: ['Sisters', 'Arabic'],
    hub: 'sisters',
  },

  // Youth programmes (id matches /community/youth)
  {
    id: 'youth',
    category: 'community',
    title: 'Youth Hub',
    summary: 'Friday-night gathering for learning, leadership, and confident Muslim identity.',
    schedule: 'Friday evenings',
    tags: ['Youth'],
    hub: 'youth',
  },
  {
    id: 'youth-sports-league',
    category: 'community',
    title: 'Youth Sports League',
    summary: 'Seasonal basketball and badminton leagues for brothers ages 14–25 with coaches and refs.',
    schedule: 'Saturdays (seasonal)',
    tags: ['Youth', 'Sports'],
    hub: 'youth',
  },
  {
    id: 'youth-dawah',
    category: 'community',
    title: 'Youth Dawah & Media Team',
    summary: 'Train youth to create reminders, film short clips, and support masjid outreach.',
    schedule: 'Biweekly Sundays',
    tags: ['Youth', 'Media'],
    hub: 'youth',
  },

  // Seniors programmes (id matches /community/seniors)
  {
    id: 'seniors',
    category: 'community',
    title: 'Seniors Hub',
    summary: 'Spiritual and social support for elders — check-ins, companionship, and care.',
    tags: ['Seniors'],
    hub: 'seniors',
  },
  {
    id: 'seniors-fiqh',
    category: 'education',
    title: 'Seniors Fiqh & Remembrance',
    summary: 'Gentle fiqh reminders and dhikr sessions designed for our elders.',
    schedule: 'Wednesdays after Dhuhr',
    tags: ['Seniors', 'Fiqh'],
    hub: 'seniors',
  },
  {
    id: 'seniors-transport',
    category: 'community',
    title: 'Seniors Ride Assistance',
    summary: 'Volunteer drivers help elders attend Jummah, appointments, and hub gatherings.',
    schedule: 'By request',
    tags: ['Seniors', 'Volunteer'],
    hub: 'seniors',
  },

  // General community
  {
    id: 'weekly',
    category: 'community',
    title: 'Weekly Gathering',
    summary: 'Fiqh Halaqa, English & Urdu Tafseer, Hadith Dars, and Jawla.',
    tags: ['Weekly'],
  },
  {
    id: 'convert-care',
    category: 'community',
    title: 'Convert Care Programme',
    summary: 'Buddy system and essentials classes for new Muslims settling into community life.',
    schedule: 'Ongoing',
    tags: ['Community', 'New Muslims'],
  },
  {
    id: 'family-night',
    category: 'community',
    title: 'Monthly Family Night',
    summary: 'Games, short reminders, and shared meals for families — a relaxed evening at the masjid.',
    schedule: 'Last Saturday each month',
    tags: ['Families', 'Community'],
  },

  // Services
  {
    id: 'nikah-service',
    category: 'service',
    title: 'Nikah — Marriage Ceremony',
    summary:
      'Qualified marriage officers conduct nikah ceremonies in accordance with Islamic law and Ontario civil requirements.',
    tags: ['Marriage', 'Service'],
  },
  {
    id: 'counselling-service',
    category: 'service',
    title: 'Marriage Counselling & Pastoral Support',
    summary: 'Confidential marriage counselling and pastoral support available through our Imams.',
    tags: ['Counselling', 'Service'],
  },
  {
    id: 'janazah-service',
    category: 'service',
    title: 'Funeral & Janazah Services',
    summary: 'Dedicated Janazah facilities are planned as part of our building development.',
    tags: ['Coming soon', 'Service'],
  },
];

export const seedAnnouncementsExtra = [
  'Help keep the masjid clean for everyone. Please dispose of garbage properly.',
  'Remember to fill the front rows and keep the lines straight.',
  'Please silence all mobile phones before Salah. Jazakum Allahu Khairan.',
  'Prayer times subject to change — confirm on the live board.',
  'Youth Hub meets every Friday after Isha — brothers ages 13+ welcome.',
  "Sisters' Halaqa continues Thursdays after Maghrib in the sisters wing.",
  'Seniors Tea & Companionship: Tuesdays 11 AM in the community lounge.',
  'Parking reminder: do not park at 25 Overlea Blvd or East York Town Centre.',
  'Register early for Evening Madressa and Sunday Madrasah — seats fill quickly.',
  'Volunteer drivers needed for Seniors Ride Assistance — contact the office.',
  'Sisters Drop-in Volleyball: Wednesday, August 12 · 8–10 PM in the IST Gym.',
  'Community Family Picnic planned for Sunday, August 24 — details on the events page.',
];
